name: Basic Program Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Verify program starts
      run: |
        # Try to import main modules to verify installation
        python -c "
        from src.stock_analysis import StockAnalysis
        from src.stock_data import StockData
        from src.visualization import StockVisualizer
        print('All modules imported successfully')
        "
